### ISSUE TITLE
Rename branch

### ISSUE THREAD

**Issue by MoNTE48** [ResurrectionRemix/external_chromium-webview#2]
Pls, rename branch on marshmallow.
error: Cannot fetch external_chromium-webview
warn: --force-broken, continuing to sync
Fetching projects: 100% (531/531), done.  
Syncing work tree:  12% (64/531)  error: in `sync -c -f -j4 --force-sync --no-clone-bundle`: revision marshmallow in external_chromium-webview not found

**Comment by akhilnarang** [comment]
Done
