### ISSUE TITLE
Remove x86 apk

### ISSUE THREAD

**Issue by MoNTE48** [ResurrectionRemix/external_chromium-webview#3]
Google combined x86, arm and arm64 on a single apkhttps://www.apkmirror.com/apk/google-inc/android-system-webview/android-system-webview-48-0-2564-71-arm-arm64-android-apk-download/
Now there is no need to hold 3 different apk.

**Comment by MoNTE48** [comment]
Ank the link above contains armv7 and armv8 libs. On my zenfone 2 (x86) on play store install apk on this link automatically. But apk not contained x86 libs, everything works fine. It seems, Google began to abandon support for a separate version of their apps for intel :)

**Comment by akhilnarang** [comment]
https://github.com/UBERMALLOW/external_chromium-webview/
We're following that, Chet still has it, let's see

**Comment by akhilnarang** [comment]
@MoNTE48 https://github.com/UBERMALLOW/external_chromium-webview/commit/f811667d8c1b6b8995eca9fd4a1f50b6dbe9cf98
